
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: data_no
        description: "The primary key for this table"
        tests:
          - unique
      - name: data_status
        description: "Status of id "
        tests:
          - not_null
      - name: dollar_price
        description: "Price in dollar "
        tests:
          - not_null
      - name: data_updated_at
        description: "Status of id updated at"